/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.amf.user.profile.model.impl;

import com.amf.user.profile.model.GeneralProfile;
import com.amf.user.profile.service.GeneralProfileLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the GeneralProfile service. Represents a row in the &quot;UserProfile_GeneralProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GeneralProfileImpl}.
 * </p>
 *
 * @author andrefabbro
 * @see GeneralProfileImpl
 * @see com.amf.user.profile.model.GeneralProfile
 * @generated
 */
public abstract class GeneralProfileBaseImpl extends GeneralProfileModelImpl
	implements GeneralProfile {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a general profile model instance should use the {@link GeneralProfile} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			GeneralProfileLocalServiceUtil.addGeneralProfile(this);
		}
		else {
			GeneralProfileLocalServiceUtil.updateGeneralProfile(this);
		}
	}
}