/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.amf.user.profile.model.impl;

import com.amf.user.profile.model.MovieInterest;
import com.amf.user.profile.service.MovieInterestLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MovieInterest service. Represents a row in the &quot;UserProfile_MovieInterest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MovieInterestImpl}.
 * </p>
 *
 * @author andrefabbro
 * @see MovieInterestImpl
 * @see com.amf.user.profile.model.MovieInterest
 * @generated
 */
public abstract class MovieInterestBaseImpl extends MovieInterestModelImpl
	implements MovieInterest {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a movie interest model instance should use the {@link MovieInterest} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MovieInterestLocalServiceUtil.addMovieInterest(this);
		}
		else {
			MovieInterestLocalServiceUtil.updateMovieInterest(this);
		}
	}
}